
name: Gradle Package

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Step 1- checking out the code
      uses: actions/checkout@v3
    
    - name: Step 2- Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Step 3-Printing files
      run: 
        ls
        
    - name: Step 4-Making Graddle file executable
      run: 
        chmod +x gradlew
        
    - name: Step 5-Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    - name: Step 6-Printing files
      run: 
        ls build      
        
    - uses: Step 7-actions/upload-artifact@v3
      with:
        name: my-artifact
        path: build/
